/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyCustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData eye_slash_regular = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash_solid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class MyCustomColors{

  MyCustomColors._();

  static const _blue = '#44D9E6';

  // construct a color from a hex code string of the form #RRGGBB
  static _hexToColor(String code){
    code = code.substring(1, 7);
    int val = code.length == 6 ? int.parse(code, radix: 16): int.parse(code) ;
    val = val + 0xff000000;
    return val;
  }

//  returns int Color code which is to be passed in Color()
  static blue() => Color(_hexToColor(_blue));

}

class MyCustomFonts{

  MyCustomFonts._();

  static const twenty = 2.457;
  static const nineteen = 2.334;
  static const eighteen = 2.211;
  static const sixteen = 1.966;

}
